# Generated by Django 6.0.4 on 2026-05-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Премиум до'),
        ),
    ]
