# Generated by Django 6.0.4 on 2026-04-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('slot_type', models.CharField(choices=[('main_weapon', 'Основное оружие'), ('off_weapon', 'Дополнительное оружие'), ('helmet', 'Шлем'), ('armor', 'Броня'), ('amplifier', 'Усилитель'), ('accessory', 'Аксессуар'), ('guardian', 'Дух-хранитель')], max_length=20, verbose_name='Тип слота')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['slot_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
                ('name_ru', models.CharField(max_length=64, verbose_name='Название')),
                ('category', models.CharField(choices=[('power', 'Мощь'), ('resistance', 'Сопротивление')], default='power', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_percent', models.BooleanField(default=False, verbose_name='В процентах')),
            ],
            options={
                'verbose_name': 'Стат',
                'verbose_name_plural': 'Статы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value', models.FloatField(verbose_name='Базовое значение')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='catalog.item')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.stat')),
            ],
            options={
                'verbose_name': 'Стат предмета',
                'verbose_name_plural': 'Статы предмета',
                'unique_together': {('item', 'stat')},
            },
        ),
    ]
