# Generated by Django 6.0.4 on 2026-04-29 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='Моя кукла', max_length=64, verbose_name='Название')),
                ('character_level', models.PositiveSmallIntegerField(default=1, verbose_name='Уровень персонажа')),
                ('stats_snapshot', models.JSONField(blank=True, default=dict)),
                ('slot_order', models.PositiveSmallIntegerField(default=0, verbose_name='Номер слота')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичная ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dolls', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Кукла',
                'verbose_name_plural': 'Куклы',
                'ordering': ['slot_order'],
            },
        ),
        migrations.CreateModel(
            name='DollSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_invested', models.PositiveSmallIntegerField(default=0)),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_points', to='calculator.doll')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skillnode')),
            ],
            options={
                'verbose_name': 'Навык куклы',
                'verbose_name_plural': 'Навыки куклы',
                'unique_together': {('doll', 'node')},
            },
        ),
        migrations.CreateModel(
            name='DollSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('main_weapon', 'Основное оружие'), ('off_weapon', 'Дополнительное оружие'), ('helmet', 'Шлем'), ('armor', 'Броня'), ('amplifier', 'Усилитель'), ('accessory', 'Аксессуар'), ('guardian', 'Дух-хранитель')], max_length=20, verbose_name='Тип слота')),
                ('grade', models.PositiveSmallIntegerField(default=0, verbose_name='Грейд (0-15)')),
                ('quality', models.FloatField(default=0.01, verbose_name='Качество (0.01-1.00)')),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='calculator.doll')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Слот куклы',
                'verbose_name_plural': 'Слоты куклы',
                'unique_together': {('doll', 'slot_type')},
            },
        ),
    ]
