# Generated by Django 6.0.4 on 2026-04-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('attack', 'Атака'), ('health', 'Здоровье'), ('defense', 'Защита')], max_length=16, verbose_name='Ветка')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок (строка сверху вниз)')),
                ('name', models.CharField(max_length=64, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('max_points', models.PositiveSmallIntegerField(default=1, verbose_name='Макс. очков (1-3)')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='CSS-класс иконки')),
            ],
            options={
                'verbose_name': 'Узел навыка',
                'verbose_name_plural': 'Узлы навыков',
                'ordering': ['branch', 'order'],
                'unique_together': {('branch', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SkillEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('vertical', 'Вертикальная'), ('diagonal', 'Диагональная')], default='vertical', max_length=16)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='skills.skillnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='skills.skillnode')),
            ],
            options={
                'verbose_name': 'Связь навыков',
                'verbose_name_plural': 'Связи навыков',
                'unique_together': {('from_node', 'to_node')},
            },
        ),
        migrations.CreateModel(
            name='SkillBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_per_point', models.FloatField(verbose_name='Значение за 1 очко')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.stat')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='skills.skillnode')),
            ],
            options={
                'verbose_name': 'Бонус навыка',
                'verbose_name_plural': 'Бонусы навыков',
                'unique_together': {('node', 'stat')},
            },
        ),
    ]
