# Generated by Django 6.0.4 on 2026-04-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skillbonus_per_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillbonus',
            name='value_level_1',
            field=models.FloatField(verbose_name='Значение за 1-й уровень'),
        ),
    ]
