# Generated by Django 6.0.4 on 2026-05-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skillbonus_value_level_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillnode',
            options={'ordering': ['section', 'branch', 'order'], 'verbose_name': 'Узел навыка', 'verbose_name_plural': 'Узлы навыков'},
        ),
        migrations.AlterUniqueTogether(
            name='skillnode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='skillnode',
            name='section',
            field=models.CharField(choices=[('attack', 'Атака'), ('defense', 'Защита'), ('health', 'Здоровье'), ('resistance', 'Сопротивление')], default='attack', max_length=16, verbose_name='Раздел'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillnode',
            name='branch',
            field=models.CharField(choices=[('1', 'Ветка 1'), ('2', 'Ветка 2'), ('3', 'Ветка 3')], max_length=4, verbose_name='Ветка'),
        ),
        migrations.AlterUniqueTogether(
            name='skillnode',
            unique_together={('section', 'branch', 'order')},
        ),
    ]
